### ISSUE TITLE
Buen trabajo!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcas-s3-evaluacion-intermedia-Fanyfa#1]
Nos animamos a mejorarlo?

1. Hacer un componente que pinte el ul, li y el componente de la card
2. Los li debe tener un key=""
3. Eliminar archivos que no usamos.

**Comment by Fanyfa** [comment]
Ya estaría todo, Carlos!

**Comment by oneeyedman** [comment]
Muy bien hecho!!
